Algoritmo "exercicio2"
//  
//  

Var
  n1, n2: real


Inicio
     escreval("digite o primeiro número")
        leia(n1)
      escreval("digite o segundo número")
        leia(n2)
         
         se n1>n2 entao
           escreva("primeiro numero maior que o segundo numero")

         se n1<n2 entao
           escreva(" segundo numero maior que primeiro numero")
           
           fimse
             fimse
Fimalgoritmo
