Algoritmo "exercicio11"

var
   primeira, segunda, terceira, media: inteiro

Inicio
      escreva("Informe a primeira nota")
        leia(primeira)
           escreva("informa a segunda nota")
             leia(segunda)
               escreva("Informe a terceira nota")
                 leia(terceira)
                 
       media <- (primeira * 2, segunda * 3, terceira * 5)/10
         escreva("A média é ", media)


Fimalgoritmo