Algoritmo "media"

Var
   media, n1, n2, n3, n4 : real
   


Inicio
    escreva("digite a primeira nota do aluno: ")
    leia(n1)
    escreva("digite a primeira nota do aluno: ")
    leia(n2)
    escreva("digite a primeira nota do aluno: ")
    leia(n3)
    escreva("digite a primeira nota do aluno: ")
    leia(n4)
    
    media <- ((n1+n2+n3+n4)/4)
    escreva (" a media do aluno é: " , media)
    se media >= 7 entao
      escreva("aluno aprovado!")


Fimalgoritmo